import Alpine from 'alpinejs';
import quickProgram from './quick-program';
Alpine.data('quickProgram', quickProgram);
import websiteTracking from './website-tracking';
Alpine.data('websiteTracking', websiteTracking);
import gethiredConnection from './gethired-connection';
Alpine.data('gethiredConnection', gethiredConnection);
import programMessenger from './program-messenger';
Alpine.data('programMessenger', programMessenger);
import gethiredPublicLanding from './gethired-public-landing';
Alpine.data('gethiredPublicLanding', gethiredPublicLanding);
window.Alpine = Alpine;
Alpine.start();
