@php
 $d=$subscriptionDashboard;
 $args=['tenantId'=>$tenant->id,'program_id'=>$program->id,'currency'=>$d['currency'],'days'=>$d['days']];
 $rewardUrl=route('reseller.commission',$args);$activityUrl=route('reseller.activity',$args);$messageUrl=route('reseller.messages',$args);$detailsUrl=route('reseller.programs.show',[$tenant->id,$program->id]);
 $money=fn($minor)=>$d['currency'].' '.number_format($minor/100,2);
 $validOffers=$offers->filter(fn($offer)=>$offer->currentVersion && $offer->currentVersion->status==='published' && $offer->currentVersion->tenant_id===$tenant->id && $offer->currentVersion->program_id===$program->id);
 $chartValues=array_values($d['daily']);$chartDates=array_keys($d['daily']);
@endphp

<div class="rbs">
 <header class="row dashboard-heading"><div><h1>Dashboard</h1><p class="muted">Track your referrals, rewards, and activity all in one place.</p></div><div class="row page-controls">@include('reseller.programs._picker')<x-portal-view-switch current="referrer" /></div></header>
 <section class="panel hero"><div class="program-identity">@include('reseller.programs._logo',['p'=>$program])<div><h2>{{ $program->name }}</h2><p class="muted">Share something you believe in. Follow the rewards you earn.</p><p class="muted campaign-context">@if($d['campaign'])Campaign: {{ $d['campaign']['starts_on'] }} – {{ $d['campaign']['ends_on'] }} · {{ $d['campaign']['state'] }} · {{ $d['tz'] }}@else Subscription Referral Program @endif · Your activity only</p></div></div><div class="program-state"><div><span class="status">Program: {{ ucfirst($program->status) }}</span> <span class="status">Membership: {{ ucfirst($membership->status) }}</span></div><a class="link" href="{{ $detailsUrl }}?tab=mechanics">Program mechanics →</a></div></section>
 <section class="panel share" x-data="{ copyStatus: '', copied: false, resetTimer: null }"><div><h2>Your personal referral link</h2><p class="muted">Send your link to someone who could benefit from {{ $program->name }}.</p>
 @if($referralLink)<div class="share-row"><input id="referral-link" aria-label="Your referral link" x-ref="referralLink" type="text" readonly value="{{ $referralLink }}" @click="$el.select()"><button class="button primary" type="button" @click="(async () => { try { await navigator.clipboard.writeText($refs.referralLink.value); copied=true; copyStatus='Link copied!'; clearTimeout(resetTimer); resetTimer=setTimeout(() => { copied=false; copyStatus=''; }, 2000); } catch(e) { $refs.referralLink.focus(); $refs.referralLink.select(); copied=false; copyStatus='Copy unavailable. Select and copy the link above.'; } })()"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path x-show="!copied" d="M8 8h12v13H8zM16 8V3H3v13h5"/><path x-show="copied" d="m5 12 4 4L19 6"/></svg><span x-text="copied ? 'Copied' : 'Copy referral link'">Copy referral link</span></button><a class="button" href="{{ \Illuminate\Support\Uri::of($referralLink)->withQuery(['preview'=>1]) }}" target="_blank" rel="noopener noreferrer">Preview link ↗</a></div><p role="status" aria-live="polite" class="muted copy-feedback" x-cloak x-show="copyStatus" x-text="copyStatus"></p>
 @else<div class="note">@if($program->status !== 'active')This program is {{ $program->status }}. Sharing is available when it is active.@elseif($membership->status !== 'active')Your membership is {{ $membership->status }}. Sharing requires an active membership.@else A referral website has not been configured for this program.@endif <a class="link" href="{{ $messageUrl }}">Message company admins →</a></div>@endif
 <div class="tracking-strip" aria-label="Referral link click statistics">
 @foreach([['click',$d['linkClicks'],'Total link clicks'],['users',$d['uniqueBrowsers'],'Unique browsers (estimated)'],['trend',$d['periodClicks'],'Clicks in the last '.$d['days'].' days']] as [$icon,$value,$label])<div class="tracking-stat"><span class="icon">@include('tenant.programs._dashboard-icon',['icon'=>$icon])</span><div><strong>{{ number_format($value) }}</strong><p class="muted">{{ $label }}</p></div></div>@endforeach
 <div class="note">Rewards follow payment eligibility rules. <details class="methodology"><summary class="link">How clicks are counted</summary><p class="muted">Short-link visits recorded since tracking was enabled. Repeat visits count as clicks. Unique browsers use a 30-day cookie, not verified people. Previews, known bots and signed-in visits by you or your company team are excluded. Earlier visits, direct website links and blocked tracking are not counted.</p></details></div></div>


 </div><img class="mascot" src="{{ asset('images/mascots/r-bunny-thumbs-up.webp') }}" alt="" width="120" height="120"></section>
 <div class="row results-toolbar"><h2>Your results <span class="muted" style="font-weight:400">· All time</span></h2><form method="GET" class="row" style="gap:8px"><input type="hidden" name="program_id" value="{{ $program->id }}"><input type="hidden" name="days" value="{{ $d['days'] }}"><label for="reward-currency" class="muted">Reward currency</label><select id="reward-currency" name="currency">@foreach($d['currencies'] as $currency)<option @selected($currency===$d['currency'])>{{ $currency }}</option>@endforeach</select><button class="button primary">Apply</button></form></div>
 <section class="metrics">
 @foreach([
 ['gift','Net recorded rewards',$money($d['net']),'After refund reversals · not a payout total',$rewardUrl],
 ['users','Paying customers',number_format($d['customers']),'Customers with a recorded '.$d['currency'].' payment',route('reseller.deals',$args)],
 ['renew','Recorded payments',number_format($d['payments']),'First payments and renewals · '.$d['currency'],$activityUrl],
 ['wallet','Ready for review',number_format($d['ready']),'Rewards past their hold · '.$d['currency'],$rewardUrl],
 ] as [$icon,$label,$value,$note,$url])<a class="panel metric" href="{{ $url }}"><div class="metric-title"><span class="icon">@include('tenant.programs._dashboard-icon',['icon'=>$icon])</span>{{ $label }}</div><strong>{{ $value }}</strong><p class="muted">{{ $note }}</p></a>@endforeach
 </section>
 <div class="main-grid"><div class="stack">
  @include('components.signup-metrics',['signupMetrics'=>$d['signupMetrics'],'signupTimezone'=>$d['tz'],'signupVariant'=>'compact'])
  @include('reseller.programs._click-chart')
  <section class="panel"><div class="row"><div><h2>Your reward activity</h2><p class="muted">Daily recorded rewards · {{ $d['currency'] }} · {{ $d['tz'] }}</p></div><nav class="range" aria-label="Reward chart range">@foreach([7,30,90] as $days)<a class="{{ $d['days']===$days?'active':'' }}" @if($d['days']===$days) aria-current="page" @endif href="{{ route('reseller.dashboard',array_replace($args,['days'=>$days,'currency'=>$d['currency']])) }}">{{ $days }}D</a>@endforeach</nav></div>
  @include('reseller.programs._daily-chart',['series'=>$d['daily'],'integerAxis'=>false,'chartLabel'=>'Daily recorded rewards for the past '.$d['days'].' days'])
  <p class="muted">{{ $d['start']->format('M j') }} – {{ $d['end']->format('M j, Y') }} · {{ $money(array_sum($chartValues)*100) }} net recorded rewards. Refunds may appear below zero.</p>
  <details class="methodology"><summary class="link" style="cursor:pointer">View daily amounts</summary><div style="max-height:180px;overflow:auto"><table><thead><tr><th>Date</th><th>Recorded reward</th></tr></thead><tbody>@foreach($d['daily'] as $date=>$amount)<tr><td>{{ $date }}</td><td>{{ $d['currency'] }} {{ number_format($amount,2) }}</td></tr>@endforeach</tbody></table></div></details>
  </section>

 </div><aside class="stack side">
  <section class="panel"><h2>Your reward status</h2><a class="line-item" href="{{ $rewardUrl }}"><span class="icon">◷</span><div class="grow"><strong>{{ $d['hold'] }} on hold</strong><p class="muted">Waiting for the hold period to end</p></div><span>›</span></a><a class="line-item" href="{{ $rewardUrl }}"><span class="icon">@include('tenant.programs._dashboard-icon',['icon'=>'gift'])</span><div class="grow"><strong>{{ $d['ready'] }} ready for company review</strong><p class="muted">Review does not mean paid</p></div><span>›</span></a><a class="line-item" href="{{ $messageUrl }}"><span class="icon">@include('tenant.programs._dashboard-icon',['icon'=>'users'])</span><div class="grow"><strong>{{ $d['unread'] }} unread messages</strong><p class="muted">Talk with this program’s admins</p></div><span>›</span></a><div class="note">Reward counts above use {{ $d['currency'] }}. Payment arrangements are handled by the company. Recorded rewards are not confirmed payouts.</div></section>
  <section class="panel"><div class="row"><h2>How you earn</h2><a href="{{ $detailsUrl }}?tab=mechanics" class="link">Full mechanics →</a></div>
  @forelse($validOffers as $offer)@php $v=$offer->currentVersion;$rules=$v->reward_rules ?? []; @endphp<div class="terms"><strong>{{ $v->reward_model==='percentage'?(float)$v->percentage_rate.'%':($v->reward_model==='fixed'?$v->currency.' '.number_format($v->fixed_amount,2):'Custom') }} reward</strong><p class="muted">{{ $offer->name }}</p><p class="muted">{{ ($rules['scope'] ?? '')==='recurring'?'Eligible payments for '.($rules['duration_months'] ?? 'the configured number of').' months from the first payment.':(($rules['scope'] ?? '')==='first_payment'?'First eligible payment only.':'See the published offer for reward eligibility.') }}</p><p class="muted">@if(isset($rules['hold_days'])){{ $rules['hold_days'] }}-day hold · @endif{{ ucfirst(str_replace('_',' ',$v->qualifying_event ?? 'See program terms')) }}</p></div>@empty<p class="muted" class="methodology">No active reward offer published yet.</p>@endforelse
  <p class="muted history-note">Historical rewards keep the offer version applied when the event was recorded.</p><a class="button full-width" href="{{ $messageUrl }}">Message company admins →</a></section>
  <section class="panel"><div class="row"><div><h2>Recent activity</h2><p class="muted">Your latest {{ $d['currency'] }} payment and refund events</p></div><a class="link" href="{{ $activityUrl }}">View all activity →</a></div>
  @if($d['recent']->isEmpty())<div class="empty"><img src="{{ asset('images/logos/referralbunny-icon-only-128x128.webp') }}" alt=""><h3>No reward activity in this currency yet</h3><p class="muted">No matching payment or refund events in {{ $d['currency'] }} for this program.</p></div>@else<div style="overflow:auto;margin-top:15px"><table><thead><tr><th>Activity</th><th>Reward</th><th>Date</th></tr></thead><tbody>@foreach($d['recent'] as $event)<tr><td>{{ $event->type==='refund'?'Refund reversal':'Subscription payment' }}<br><span class="muted">{{ ucfirst(str_replace('_',' ',$event->status)) }}</span></td><td>{{ $money($event->reward_minor) }}</td><td>{{ \Carbon\Carbon::parse($event->occurred_at,'UTC')->setTimezone($d['tz'])->format('M j, Y') }}</td></tr>@endforeach</tbody></table></div>@endif
  </section>
 </aside></div>
</div>
