@php
 $s=$subscription; $terms=$performance['financials']['terms']; $signals=$performance['financials']['signals'];
 $money=fn($n)=>$s['currency'].' '.number_format($n,2);
 $values=array_values($s['daily']); $days=array_keys($s['daily']); $max=max(1,max($values),$s['average'] ?? 0)*1.2;
 $x=fn($i)=>58+($i/max(1,count($values)-1))*780; $y=fn($v)=>245-($v/$max)*205;
 $actualIndices=array_values(array_filter(array_keys($values),fn($i)=>$days[$i]<=now($s['tz'])->toDateString()));
 $points=implode(' ',array_map(fn($i)=>$x($i).','.$y($values[$i]),$actualIndices));
 $lastActual=$actualIndices ? end($actualIndices) : 0;
 $targetPoints=[];foreach($s['targetDaily'] as $i=>$v) if($v!==null)$targetPoints[]=$x($i).','.$y($v);
 $recordArgs=['tenantId'=>$tenant->id,'programId'=>$program->id,'from'=>$s['from']->toDateString(),'to'=>$s['to']->toDateString(),'currency'=>$s['currency']];
 $clicksUrl=route('tenant.programs.clicks',$recordArgs);
 $recordsUrl=route('tenant.programs.subscription-records',$recordArgs);
 $connectionUrl=route('tenant.quick-program.connection',[$tenant->id,$program->id]);
 $manage=route('tenant.programs.workspace',[$tenant->id,$program->id]);
@endphp

<div class="rb-sub" x-data="{}">
 <header class="panel hero">
  <div class="row"><div><span class="eyebrow">SUBSCRIPTION REFERRAL PROGRAM</span><h1>{{ $program->name }} <span class="status">{{ ucfirst($program->status) }}</span></h1><p class="muted">Turn your customers into growth partners.</p></div>
   <a href="{{ $connectionUrl }}" class="panel connection-card" style="padding:12px 17px;color:inherit;text-decoration:none"><strong>{{ $s['connection']?->platform === 'gethired' ? 'GetHired account connected' : 'Connection setup' }}</strong><p class="muted">Last event: {{ $s['connection']?->last_event_at?->diffForHumans() ?? 'No events received' }}</p><p class="muted">Check signup & payment tracking →</p></a></div>
  <div class="row"><div class="terms">
   @forelse($terms as $term)<div class="term"><span class="symbol">✧</span><div><strong>{{ $term['label'] }} reward</strong><p class="muted">{{ $term['name'] }}</p></div></div><div class="term"><span class="symbol">↻</span><div><strong>Reward duration</strong><p class="muted" style="max-width:210px">{{ $term['scope'] }}</p></div></div><div class="term"><span class="symbol">◷</span><div><strong>{{ $term['hold'] }}-day hold</strong><p class="muted">Before reward review</p></div></div>@empty<p class="muted">Publish an offer to define rewards.</p>@endforelse
  </div><a class="button primary" href="{{ $manage }}">Manage program →</a></div>
  <div class="row campaign-row"><div><strong>Campaign duration</strong><p class="muted">@if($s['campaign']){{ $s['campaign']['starts_on'] }} – {{ $s['campaign']['ends_on'] }} · {{ $s['campaign']['days'] }} days · {{ $s['campaign']['state'] }}@else No campaign dates set · dashboard shows the last 30 days.@endif</p></div>@can('update',$program)<button class="button" type="button" @click="$refs.durationDialog.showModal()">{{ $s['campaign'] ? 'Edit duration' : 'Set duration' }}</button>@endcan</div>
  <form class="filters dashboard-filters" method="GET"><input type="hidden" name="program_id" value="{{ $program->id }}"><div><label for="dash-from">From</label><input id="dash-from" type="date" name="from" value="{{ $s['from']->toDateString() }}" required></div><div><label for="dash-to">To</label><input id="dash-to" type="date" name="to" value="{{ $s['to']->toDateString() }}" required></div><div><label for="dash-currency">Currency</label><select id="dash-currency" name="currency">@foreach($s['currencies'] as $c)<option @selected($c===$s['currency'])>{{ $c }}</option>@endforeach</select></div><button class="button">Apply filters</button>@if($s['campaign'])<a class="button" href="{{ route('tenant.dashboard',['tenantId'=>$tenant->id,'program_id'=>$program->id,'currency'=>$s['currency']]) }}">Full campaign</a>@endif<span class="muted">{{ $s['tz'] }} · Recorded activity</span><a class="mechanics-link" href="{{ $manage }}?tab=mechanics">Program mechanics →</a></form>
 </header>
 @if($errors->any())<div class="hint" role="alert">{{ $errors->first() }}</div>@endif
 @if(session('success'))<div class="hint" role="status">{{ session('success') }}</div>@endif
 @if($s['connection']?->platform === 'gethired')
 <section class="hint" x-data="{ status: null, failed: false, async init() { try { const response = await fetch(@js(route('tenant.quick-program.gethired.status',[$tenant->id,$program->id])), { headers: { Accept: 'application/json' } }); if (!response.ok) throw new Error(); this.status = await response.json(); } catch(e) { this.failed = true; } } }">
 <strong>GetHired tracking</strong> · <span x-text="failed ? 'Status unavailable—open connection details.' : (!status ? 'Checking connection…' : 'Account: ' + status.account + ' · Signups: ' + status.signups + ' · Payments: ' + ({not_available:'not enabled',authorization_required:'authorization required',ready:'ready',receiving:'receiving',attention:'needs attention'}[status.payments] || 'not verified'))">Checking connection…</span>
 <a href="{{ $connectionUrl }}" style="color:#7734ff;margin-left:10px">Connection details →</a>
 </section>
 @endif
 <section class="cards">
 @foreach([
 ['revenue','Net referral revenue',$money($s['revenue']),'Payments less refunds, excluding tax'],
 ['click','Clicks',number_format($s['clicks']),'Short-link visits · selected dates'],
 ['users','Signups',$s['signupMetrics']['synced_at']?number_format($s['signupMetrics']['signups']):'—','Verified referred signups · selected dates'],
 ['users','First-time paying customers',number_format(array_sum($values)),'First payment in period · includes later refunds · all currencies'],
 ['gift','Net recorded rewards',$money($s['rewards']),'Calculated, not paid out'],
 ['wallet','Revenue after rewards',$money($s['revenue']-$s['rewards']),'Before other costs']
 ] as [$icon,$label,$value,$note])<article class="panel card"><div class="card-label"><span class="icon">@include('tenant.programs._dashboard-icon',['icon'=>$icon])</span>{{ $label }}</div><span @if($label==='Clicks') title="Recorded short-link visits from all referrers in this program. Repeat visits count; previews and known bots are excluded. Tracking starts from activation, and currency does not affect clicks." @endif>@if($label==='Clicks')<a class="value" style="color:inherit;text-decoration:none" aria-label="View click report: {{ $value }} clicks" href="{{ $clicksUrl }}">{{ $value }}</a>@else<a class="value" style="color:inherit;font-weight:750;text-decoration:none" href="{{ $label==='Signups' ? $clicksUrl : ($label==='First-time paying customers' ? '#referral-daily-data' : $recordsUrl) }}">{{ $value }}</a>@endif</span><p class="muted">{{ $note }}</p></article>@endforeach
 </section>
 <section class="middle">
  <div class="panel analytics-panel"><div class="row"><div><h2>Referrals vs target</h2><p class="muted">Daily new paying referred customers · {{ $s['from']->format('M j') }}–{{ $s['to']->format('M j, Y') }}</p></div>@can('update',$program)<button class="button primary" @click="$refs.targetDialog.showModal()">{{ $s['target'] ? 'Edit target' : '+ Add target' }}</button>@endcan</div>
  <div class="row" style="margin:17px 0"><div class="legend"><span style="color:#7734ff">● Actual daily referrals</span><span style="color:#bc81ee">┄ Target daily average</span></div><div class="filters">@foreach([7,30,90,365] as $n)<a class="button" style="padding:5px 8px" href="{{ route('tenant.dashboard',['tenantId'=>$tenant->id,'program_id'=>$program->id,'from'=>now($s['tz'])->subDays($n-1)->toDateString(),'to'=>now($s['tz'])->toDateString(),'currency'=>$s['currency']]) }}">{{ $n===365?'12M':$n.'D' }}</a>@endforeach</div></div>
  <svg class="chart" viewBox="0 0 870 290" role="img" aria-label="Daily actual referrals compared with the target daily average"><defs><linearGradient id="rb-referral-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#9450ff" stop-opacity=".25"/><stop offset="100%" stop-color="#9450ff" stop-opacity=".025"/></linearGradient></defs>
   @for($i=0;$i<=4;$i++)<line x1="58" x2="838" y1="{{ $y($max*$i/4) }}" y2="{{ $y($max*$i/4) }}" stroke="#eee8fb"/><text x="45" y="{{ $y($max*$i/4)+4 }}" text-anchor="end" fill="#8676a6" font-size="11">{{ round($max*$i/4,1) }}</text>@endfor
   @if($actualIndices)<polygon points="58,245 {{ $points }} {{ $x($lastActual) }},245" fill="url(#rb-referral-fill)"/><polyline points="{{ $points }}" fill="none" stroke="#7939ff" stroke-width="2.5"/>@endif
   @if(count($targetPoints)===1)<circle cx="{{ explode(',',$targetPoints[0])[0] }}" cy="{{ explode(',',$targetPoints[0])[1] }}" r="4" fill="#b379df"/>@endif
   @if($targetPoints)<polyline points="{{ implode(' ',$targetPoints) }}" fill="none" stroke="#b379df" stroke-width="2.5" stroke-dasharray="8 6"/>@endif
   @foreach($values as $i=>$value)@continue($days[$i]>now($s['tz'])->toDateString())<circle cx="{{ $x($i) }}" cy="{{ $y($value) }}" r="{{ count($values)>100?1:3 }}" fill="#7837ff"><title>{{ $days[$i] }}: {{ $value }} referrals{{ $s['targetDaily'][$i]!==null ? ', target '.round($s['targetDaily'][$i],2) : '' }}</title></circle>@endforeach
   @foreach(array_unique([0,(int)floor((count($days)-1)/2),count($days)-1]) as $i)<text x="{{ $x($i) }}" y="275" text-anchor="{{ $i===0?'start':($i===count($days)-1?'end':'middle') }}" fill="#8676a6" font-size="11">{{ $days[$i] }}</text>@endforeach
  </svg>
  <div class="hint">@if($s['target'])<strong>{{ number_format($s['average'],2) }} referrals/day target</strong> · {{ number_format($s['target']->total) }} total from {{ $s['target']->starts_on }} to {{ $s['target']->ends_on }}.<br>{{ number_format(array_sum($values)) }} actual in this view · {{ number_format(array_sum($s['targetDaily']),2) }} expected within target dates.@else Set a referral total and dates to compare your daily results with a target.@endif</div>
  <p class="muted">A referral counts once on the customer’s first recorded payment. Renewals are excluded. Future dates are not yet results; the target line appears only within its saved dates.</p>

  </div>
  <aside class="panel attention-panel"><h2>Needs attention</h2><p class="muted">Current program status · all dates</p>
   <a class="attention" href="{{ route('tenant.programs.subscription-records',$recordArgs+['queue'=>'ready']) }}"><span class="icon">@include('tenant.programs._dashboard-icon',['icon'=>'gift'])</span><div><strong>{{ $signals['ready'] }} rewards ready for review</strong><p class="muted">Hold period completed</p></div><span>›</span></a>
   <a class="attention" href="{{ route('tenant.quick-program.connection',[$tenant->id,$program->id]) }}"><span class="icon">⌁</span><div><strong>Website tracking</strong><p class="muted">Review connection and delivery status</p></div><span>›</span></a>
   <a class="attention" href="{{ route('tenant.messages',['tenantId'=>$tenant->id,'program_id'=>$program->id]) }}"><span class="icon">☏</span><div><strong>{{ $s['unread'] }} unread messages</strong><p class="muted">Program conversations</p></div><span>›</span></a>
   <a class="attention" href="{{ route('tenant.programs.subscription-records',$recordArgs+['queue'=>'hold']) }}"><span class="icon">◷</span><div><strong>{{ $signals['on_hold'] }} rewards on hold</strong><p class="muted">Waiting for eligibility review</p></div></a>
   <div class="hint">Recorded rewards are not confirmed payouts. Review reward and payout arrangements with your team.</div><a class="button primary" style="display:block;text-align:center" href="{{ $recordsUrl }}">View payment & reward records →</a>
  </aside>
 </section>
 <section class="bottom"><div class="panel"><div class="row"><div><h2>Top referrers</h2><p class="muted">Ranked by net revenue · selected dates and currency</p></div><a href="{{ $manage }}?tab=members" style="color:#8134ff">View members →</a></div><div style="overflow:auto;margin-top:14px"><table><thead><tr><th>#</th><th>Referrer</th><th>Net revenue</th><th>Rewards</th></tr></thead><tbody>@forelse($s['top'] as $r)<tr><td>{{ $loop->iteration }}</td><td><span class="avatar">{{ mb_substr($r['name'],0,1) }}</span><a style="color:#7437c7" href="{{ route('tenant.programs.subscription-records',$recordArgs+['referrer'=>$r['id']]) }}">{{ $r['name'] }}</a></td><td>{{ $money($r['revenue']) }}</td><td>{{ $money($r['rewards']) }}</td></tr>@empty<tr><td colspan="4" class="muted">Your top referrers will appear after attributed payments arrive.</td></tr>@endforelse</tbody></table></div></div>
 <div class="panel journey-panel"><h2>Referral journey</h2><p class="muted">Selected period · available tracking</p><div class="row"><div style="flex:1;min-width:230px"><div class="journey"><div class="step"><strong>{{ number_format($s['clicks']) }}</strong><span class="muted">Clicks</span></div><span>→</span><div class="step"><strong>{{ $s['signupMetrics']['synced_at']?number_format($s['signupMetrics']['signups']):'—' }}</strong><span class="muted">Referred signups</span></div><span>→</span><div class="step"><strong>{{ array_sum($values) }}</strong><span class="muted">First paid</span></div></div><p class="muted">Counts use each event’s date; they are not a single visitor cohort. Signup reporting comes from verified GetHired registrations.</p></div><div class="journey-mascot"><img src="{{ asset('images/mascots/r-bunny-thumbs-up.webp') }}" alt="Referral Bunny mascot" width="140" height="140"><strong>Grow your next cohort</strong><br><a class="button" style="margin-top:9px" href="{{ $manage }}?tab=members">Manage referrers →</a></div></div></div></section>
  <details id="referral-daily-data" class="panel daily-data" open><summary class="muted" style="cursor:pointer">View daily data</summary><div style="max-height:200px;overflow:auto"><table><thead><tr><th>Date</th><th>Actual</th><th>Target</th></tr></thead><tbody>@foreach($s['daily'] as $day=>$count)<tr><td>{{ $day }}</td><td>{{ $day>now($s['tz'])->toDateString()?'Not yet due':$count }}</td><td>{{ $s['target'] && $day >= $s['target']->starts_on && $day <= $s['target']->ends_on ? number_format($s['average'],2) : '—' }}</td></tr>@endforeach</tbody></table></div></details>
 <dialog x-ref="targetDialog"><form method="POST" action="{{ route('tenant.programs.referral-target',[$tenant->id,$program->id]) }}">@csrf<div class="row"><h2>{{ $s['target']?'Edit':'Add' }} referral target</h2><button class="button" type="button" @click="$refs.targetDialog.close()" aria-label="Close target dialog">×</button></div><p class="muted" style="margin:10px 0 18px">Set a total number of new paying referred customers. We divide it evenly across these dates, including both the first and last day.</p><label for="target-total">Total referrals</label><input id="target-total" type="number" name="total" min="1" max="100000000" required value="{{ old('total',$s['target']?->total) }}"><label for="target-start">Start date</label><input id="target-start" @readonly($s['campaign']) type="date" name="starts_on" required value="{{ old('starts_on',$s['campaign']['starts_on'] ?? $s['target']?->starts_on ?? $s['from']->toDateString()) }}"><label for="target-end">End date</label><input id="target-end" @readonly($s['campaign']) type="date" name="ends_on" required value="{{ old('ends_on',$s['campaign']['ends_on'] ?? $s['target']?->ends_on ?? $s['to']->toDateString()) }}"><p class="muted">@if($s['campaign'])Dates follow your campaign duration. Edit duration to change them; the total target stays the same and the daily average recalculates.@else Set campaign duration above to keep target dates linked to your program.@endif This target is shared by company admins for this program. Editing it replaces the previous target.</p><button class="button primary" style="width:100%;margin-top:15px">Save target</button></form></dialog>
 <dialog x-ref="durationDialog"><form method="POST" action="{{ route('tenant.programs.campaign-duration',[$tenant->id,$program->id]) }}">@csrf
 <div class="row"><h2>Campaign duration</h2><button class="button" type="button" @click="$refs.durationDialog.close()" aria-label="Close duration dialog">×</button></div>
 <p class="muted" style="margin:12px 0">Set the campaign’s first and last day in {{ $s['tz'] }}. Both days are included.</p>
 @if($errors->duration->any())<p role="alert" style="color:#be123c">{{ $errors->duration->first() }}</p>@endif
 <label for="campaign-start">Campaign start date</label><input id="campaign-start" type="date" name="campaign_start" required value="{{ old('campaign_start',$s['campaign']['starts_on'] ?? $s['target']?->starts_on ?? $s['from']->toDateString()) }}">
 <label for="campaign-end">Campaign end date</label><input id="campaign-end" type="date" name="campaign_end" required value="{{ old('campaign_end',$s['campaign']['ends_on'] ?? $s['target']?->ends_on ?? $s['to']->toDateString()) }}">
 <p class="muted">The dashboard opens to the full campaign. Existing target totals are spread evenly over the new dates. These dates do not change your reward duration or automatically pause the program.</p>
 <button class="button primary" style="width:100%;margin-top:15px">Save campaign duration</button></form></dialog>
 @if($errors->duration->any())<span x-init="$nextTick(() => $refs.durationDialog.showModal())"></span>@endif
</div>
