<?php

/**
 * Philippine Standard Geographic Code (PSGC) — provinces and their municipalities/cities.
 * Used for LGU IDS deal import Province/Municipality dropdowns.
 */
return [

    'provinces' => [
        'Abra', 'Agusan del Norte', 'Agusan del Sur', 'Aklan', 'Albay',
        'Antique', 'Apayao', 'Aurora', 'Basilan', 'Bataan', 'Batanes',
        'Batangas', 'Benguet', 'Biliran', 'Bohol', 'Bukidnon',
        'Bulacan', 'Cagayan', 'Camarines Norte', 'Camarines Sur',
        'Camiguin', 'Capiz', 'Catanduanes', 'Cavite', 'Cebu',
        'Compostela Valley', 'Cotabato', 'Davao de Oro', 'Davao del Norte',
        'Davao del Sur', 'Davao Occidental', 'Davao Oriental',
        'Dinagat Islands', 'Eastern Samar', 'Guimaras', 'Ifugao',
        'Ilocos Norte', 'Ilocos Sur', 'Iloilo', 'Isabela', 'Kalinga',
        'La Union', 'Laguna', 'Lanao del Norte', 'Lanao del Sur',
        'Leyte', 'Maguindanao', 'Maguindanao del Norte', 'Maguindanao del Sur',
        'Marinduque', 'Masbate', 'Metro Manila', 'Misamis Occidental',
        'Misamis Oriental', 'Mountain Province', 'Negros Occidental',
        'Negros Oriental', 'Northern Samar', 'Nueva Ecija', 'Nueva Vizcaya',
        'Occidental Mindoro', 'Oriental Mindoro', 'Palawan', 'Pampanga',
        'Pangasinan', 'Quezon', 'Quirino', 'Rizal', 'Romblon',
        'Samar', 'Sarangani', 'Shariff Kabunsuan', 'Siquijor',
        'Sorsogon', 'South Cotabato', 'Southern Leyte', 'Sultan Kudarat',
        'Sulu', 'Surigao del Norte', 'Surigao del Sur', 'Tawi-Tawi',
        'Zambales', 'Zamboanga del Norte', 'Zamboanga del Sur',
        'Zamboanga Sibugay',
    ],

    'municipalities' => [
        'Metro Manila' => [
            'Caloocan', 'Las Piñas', 'Makati', 'Malabon', 'Mandaluyong',
            'Manila', 'Marikina', 'Muntinlupa', 'Navotas', 'Parañaque',
            'Pasay', 'Pasig', 'Pateros', 'Quezon City', 'San Juan',
            'Taguig', 'Valenzuela',
        ],
        'Cebu' => [
            'Alcantara', 'Alcoy', 'Alegria', 'Aloguinsan', 'Argao',
            'Asturias', 'Badian', 'Balamban', 'Bantayan', 'Barili',
            'Bogo', 'Boljoon', 'Borbon', 'Carmen', 'Catmon',
            'Cebu City', 'Compostela', 'Consolacion', 'Cordova', 'Daanbantayan',
            'Dalaguete', 'Danao', 'Dumanjug', 'Ginatilan', 'Lapu-Lapu',
            'Liloan', 'Madridejos', 'Malabuyoc', 'Mandaue', 'Medellin',
            'Minglanilla', 'Moalboal', 'Naga', 'Oslob', 'Pilar',
            'Pinamungajan', 'Poro', 'Ronda', 'Samboan', 'San Fernando',
            'San Francisco', 'San Remigio', 'Santa Fe', 'Santander',
            'Sibonga', 'Sogod', 'Tabogon', 'Tabuelan', 'Talisay',
            'Toledo', 'Tuburan', 'Tudela',
        ],
        'Batangas' => [
            'Agoncillo', 'Alitagtag', 'Balayan', 'Balete', 'Batangas City',
            'Bauan', 'Calaca', 'Calatagan', 'Cuenca', 'Ibaan',
            'Laurel', 'Lemery', 'Lian', 'Lipa', 'Lobo',
            'Mabini', 'Malvar', 'Mataas na Kahoy', 'Nasugbu', 'Padre Garcia',
            'Rosario', 'San Jose', 'San Juan', 'San Luis', 'San Nicolas',
            'San Pascual', 'Santa Teresita', 'Santo Tomas', 'Taal',
            'Talisay', 'Tanauan', 'Taysan', 'Tingloy', 'Tuy',
        ],
        'Bulacan' => [
            'Angat', 'Balagtas', 'Baliuag', 'Bocaue', 'Bulakan',
            'Bustos', 'Calumpit', 'Doña Remedios Trinidad', 'Guiguinto',
            'Hagonoy', 'Malolos', 'Marilao', 'Meycauayan', 'Norzagaray',
            'Obando', 'Pandi', 'Paombong', 'Plaridel', 'Pulilan',
            'San Ildefonso', 'San Jose del Monte', 'San Miguel', 'San Rafael',
            'Santa Maria',
        ],
        'Cavite' => [
            'Alfonso', 'Amadeo', 'Bacoor', 'Carmona', 'Cavite City',
            'Dasmariñas', 'General Emilio Aguinaldo', 'General Mariano Alvarez',
            'General Trias', 'Imus', 'Indang', 'Kawit', 'Magallanes',
            'Maragondon', 'Mendez', 'Naic', 'Noveleta', 'Rosario',
            'Silang', 'Tanza', 'Tagaytay', 'Ternate', 'Trece Martires',
        ],
        'Laguna' => [
            'Alaminos', 'Bay', 'Biñan', 'Cabuyao', 'Calamba',
            'Calauan', 'Cavinti', 'Famy', 'Kalayaan', 'Liliw',
            'Los Baños', 'Luisiana', 'Lumban', 'Mabitac', 'Magdalena',
            'Majayjay', 'Nagcarlan', 'Pakil', 'Pagsanjan', 'Pila',
            'Rizal', 'San Pablo', 'San Pedro', 'Santa Cruz',
            'Santa Maria', 'Santa Rosa', 'Siniloan', 'Victoria',
        ],
        'Rizal' => [
            'Angono', 'Antipolo', 'Baras', 'Binangonan', 'Cainta',
            'Cardona', 'Jala-Jala', 'Morong', 'Pililla', 'Rodriguez',
            'San Mateo', 'Tanay', 'Taytay', 'Teresa',
        ],
        'Pampanga' => [
            'Angeles', 'Apalit', 'Arayat', 'Bacolor', 'Candaba',
            'Floridablanca', 'Guagua', 'Lubao', 'Mabalacat', 'Macabebe',
            'Magalang', 'Masantol', 'Mexico', 'Minalin', 'Porac',
            'San Fernando', 'San Luis', 'San Simon', 'Santa Ana',
            'Santa Rita', 'Santo Tomas', 'Sasmuan',
        ],
        'Pangasinan' => [
            'Agno', 'Aguilar', 'Alaminos', 'Alcala', 'Asingan',
            'Balungao', 'Bani', 'Basista', 'Bautista', 'Bayambang',
            'Binalonan', 'Binmaley', 'Bolinao', 'Bugallon', 'Burgos',
            'Calasiao', 'Dagupan', 'Dasol', 'Infanta', 'Labrador',
            'Laoac', 'Lingayen', 'Mabini', 'Malasiqui', 'Manaoag',
            'Mangaldan', 'Mangatarem', 'Mapandan', 'Natividad', 'Pozorrubio',
            'Rosales', 'San Carlos', 'San Fabian', 'San Jacinto',
            'San Manuel', 'San Nicolas', 'San Quintin', 'Santa Barbara',
            'Santa Maria', 'Santo Tomas', 'Sison', 'Sual', 'Tayug',
            'Umingan', 'Urbiztondo', 'Urdaneta', 'Villasis',
        ],
        'Iloilo' => [
            'Ajuy', 'Alimodian', 'Anilao', 'Badiangan', 'Balasan',
            'Banate', 'Barotac Nuevo', 'Barotac Viejo', 'Batad', 'Bingawan',
            'Cabatuan', 'Calinog', 'Carles', 'Concepcion', 'Dingle',
            'Dueñas', 'Dumangas', 'Estancia', 'Guimbal', 'Igbaras',
            'Iloilo City', 'Janiuay', 'Lambunao', 'Leganes', 'Lemery',
            'Leon', 'Maasin', 'Miagao', 'Mina', 'New Lucena',
            'Oton', 'Passi', 'Pavia', 'Pototan', 'San Dionisio',
            'San Enrique', 'San Joaquin', 'San Miguel', 'San Rafael',
            'Santa Barbara', 'Sara', 'Tigbauan', 'Tubungan', 'Zarraga',
        ],
        'Davao del Sur' => [
            'Bansalan', 'Davao City', 'Digos', 'Hagonoy', 'Kiblawan',
            'Magsaysay', 'Malalag', 'Matanao', 'Padada', 'Santa Cruz',
            'Sulop',
        ],
        'Davao del Norte' => [
            'Asuncion', 'Braulio E. Dujali', 'Carmen', 'Kapalong', 'New Corella',
            'Panabo', 'San Isidro', 'Santo Tomas', 'Tagum', 'Talaingod',
        ],
        'Zamboanga del Sur' => [
            'Aurora', 'Bayog', 'Dimataling', 'Dinas', 'Dumalinao',
            'Dumingag', 'Guipos', 'Josefina', 'Kumalarang', 'Labangan',
            'Lakewood', 'Lapuyan', 'Mahayag', 'Margosatubig', 'Midsalip',
            'Molave', 'Pagadian', 'Pitogo', 'Ramon Magsaysay', 'San Miguel',
            'San Pablo', 'Sominot', 'Tabina', 'Tambulig', 'Tigbao',
            'Tukuran', 'Tudela', 'Zamboanga City',
        ],
        'South Cotabato' => [
            'Banga', 'General Santos', 'Koronadal', 'Lake Sebu',
            'Norala', 'Polomolok', 'Santo Niño', 'Surallah', 'T\'Boli',
            'Tampakan', 'Tantangan', 'Tupi',
        ],
        'Misamis Oriental' => [
            'Alubijid', 'Balingasag', 'Balingoan', 'Binuangan', 'Cagayan de Oro',
            'Claveria', 'El Salvador', 'Gingoog', 'Gitagum', 'Initao',
            'Jasaan', 'Kinoguitan', 'Lagonglong', 'Laguindingan', 'Libertad',
            'Lugait', 'Magsaysay', 'Manticao', 'Medina', 'Naawan',
            'Opol', 'Salay', 'Sugbongcogon', 'Tagoloan', 'Talisayan',
            'Villanueva',
        ],
        'Nueva Ecija' => [
            'Aliaga', 'Bongabon', 'Cabanatuan', 'Cabiao', 'Carranglan',
            'Cuyapo', 'Gabaldon', 'Gapan', 'General Mamerto Natividad',
            'General Tinio', 'Guimba', 'Jaen', 'Laur', 'Licab',
            'Llanera', 'Lupao', 'Munoz', 'Nampicuan', 'Palayan',
            'Pantabangan', 'Peñaranda', 'Quezon', 'Rizal', 'San Antonio',
            'San Isidro', 'San Jose', 'San Leonardo', 'Santa Rosa',
            'Santo Domingo', 'Talavera', 'Talugtug', 'Zaragoza',
        ],
        'Albay' => [
            'Bacacay', 'Camalig', 'Daraga', 'Guinobatan', 'Jovellar',
            'Legazpi', 'Libon', 'Ligao', 'Malilipot', 'Malinao',
            'Manito', 'Oas', 'Pio Duran', 'Polangui', 'Rapu-Rapu',
            'Santo Domingo', 'Tabaco', 'Tiwi',
        ],
        'Quezon' => [
            'Agdangan', 'Alabat', 'Atimonan', 'Buenavista', 'Burdeos',
            'Calauag', 'Candelaria', 'Catanauan', 'Dolores', 'General Luna',
            'General Nakar', 'Guinayangan', 'Gumaca', 'Infanta', 'Jomalig',
            'Lopez', 'Lucban', 'Lucena', 'Macalelon', 'Mauban',
            'Mulanay', 'Padre Burgos', 'Pagbilao', 'Panukulan', 'Patnanungan',
            'Perez', 'Pitogo', 'Plaridel', 'Polillo', 'Quezon',
            'Real', 'Sampaloc', 'San Andres', 'San Antonio', 'San Francisco',
            'San Narciso', 'Sariaya', 'Tagkawayan', 'Tayabas', 'Tiaong',
            'Unson',
        ],
        'Cagayan' => [
            'Abulug', 'Alcala', 'Allacapan', 'Amulung', 'Aparri',
            'Baggao', 'Ballesteros', 'Buguey', 'Calayan', 'Camalaniugan',
            'Claveria', 'Enrile', 'Gattaran', 'Gonzaga', 'Iguig',
            'Lal-lo', 'Lasam', 'Pamplona', 'Peñablanca', 'Piat',
            'Rizal', 'Sanchez-Mira', 'Santa Ana', 'Santa Praxedes',
            'Santa Teresita', 'Santo Niño', 'Solana', 'Tuguegarao', 'Tuao',
        ],
        'Ilocos Norte' => [
            'Adams', 'Bacarra', 'Badoc', 'Bangui', 'Banna',
            'Batac', 'Burgos', 'Carasi', 'Currimao', 'Dingras',
            'Dumalneg', 'Laoag', 'Marcos', 'Nueva Era', 'Pagudpud',
            'Paoay', 'Pasuquin', 'Piddig', 'Pinili', 'San Nicolas',
            'Sarrat', 'Solsona', 'Vintar',
        ],
        'Ilocos Sur' => [
            'Alilem', 'Banayoyo', 'Bantay', 'Burgos', 'Cabugao',
            'Candon', 'Caoayan', 'Cervantes', 'Galimuyod', 'Gregorio del Pilar',
            'Lidlidda', 'Magsingal', 'Nagbukel', 'Narvacan', 'Quirino',
            'Salcedo', 'San Emilio', 'San Esteban', 'San Ildefonso',
            'San Juan', 'San Vicente', 'Santa', 'Santa Catalina',
            'Santa Cruz', 'Santa Lucia', 'Santa Maria', 'Santiago',
            'Santo Domingo', 'Sigay', 'Sinait', 'Sugpon', 'Suyo',
            'Tagudin', 'Vigan',
        ],
        'La Union' => [
            'Agoo', 'Aringay', 'Bacnotan', 'Bagulin', 'Balaoan',
            'Bangar', 'Bauang', 'Burgos', 'Caba', 'Luna',
            'Naguilian', 'Pugo', 'Rosario', 'San Fernando', 'San Gabriel',
            'San Juan', 'Santo Tomas', 'Santol', 'Sudipen', 'Tubao',
        ],
        'Benguet' => [
            'Atok', 'Baguio', 'Bakun', 'Bokod', 'Buguias',
            'Itogon', 'Kabayan', 'Kapangan', 'Kibungan', 'La Trinidad',
            'Mankayan', 'Sablan', 'Tuba', 'Tublay',
        ],
        'Isabela' => [
            'Alicia', 'Angadanan', 'Aurora', 'Benito Soliven', 'Burgos',
            'Cabagan', 'Cabatuan', 'Cauayan', 'Cordon', 'Delfin Albano',
            'Dinapigue', 'Divilacan', 'Echague', 'Gamu', 'Ilagan',
            'Jones', 'Luna', 'Maconacon', 'Mallig', 'Naguilian',
            'Palanan', 'Quezon', 'Quirino', 'Ramon', 'Reina Mercedes',
            'Roxas', 'San Agustin', 'San Guillermo', 'San Isidro', 'San Manuel',
            'San Mariano', 'San Mateo', 'San Pablo', 'Santa Maria',
            'Santiago', 'Santo Tomas', 'Tumauini',
        ],
    ],

];
