<?php

return [
    // NOTE: 'lgu_ids' is a LOCKED tenant-specific template — NOT listed here.
    // LGU IDS uses app/Services/LguIds/LguIdsPricingService + LguIdsImportService exclusively.

    'default' => [
        'label'           => 'Generic',
        'description'     => 'Standard deal import for all industries.',
        'required_fields' => ['deal_name', 'deal_amount', 'referrer_email', 'organization_name'],
        'optional_fields' => [
            'deal_stage', 'deal_status', 'deal_start_date', 'expected_close_date',
            'contact_name', 'contact_email', 'contact_phone', 'product_or_service',
            'deal_source', 'notes', 'tags', 'partner_emails', 'currency',
            'internal_reference_id', 'region', 'owner_email',
        ],
        'default_values'  => [
            'deal_stage'   => 'introduction',
            'deal_status'  => 'active',
            'currency'     => 'PHP',
        ],
        'aliases' => [
            'deal name'              => 'deal_name',
            'opportunity name'       => 'deal_name',
            'opportunity'            => 'deal_name',
            'deal'                   => 'deal_name',
            'deal amount'            => 'deal_amount',
            'amount'                 => 'deal_amount',
            'value'                  => 'deal_amount',
            'estimated value'        => 'deal_amount',
            'contract value'         => 'deal_amount',
            'referrer email'         => 'referrer_email',
            'reseller email'         => 'referrer_email',
            'organization'           => 'organization_name',
            'company'                => 'organization_name',
            'company name'           => 'organization_name',
            'client'                 => 'organization_name',
            'customer'               => 'organization_name',
            'organization name'      => 'organization_name',
            'partner emails'         => 'partner_emails',
            'partner email'          => 'partner_emails',
            'stage'                  => 'deal_stage',
            'status'                 => 'deal_status',
            'start date'             => 'deal_start_date',
            'deal start date'        => 'deal_start_date',
            'import date'            => 'deal_start_date',
            'close date'             => 'expected_close_date',
            'expected close date'    => 'expected_close_date',
            'expected_close_date'    => 'expected_close_date',
            'contact'                => 'contact_name',
            'contact person'         => 'contact_name',
            'contact name'           => 'contact_name',
            'contact email'          => 'contact_email',
            'contact phone'          => 'contact_phone',
            'product'                => 'product_or_service',
            'service'                => 'product_or_service',
            'product or service'     => 'product_or_service',
            'source'                 => 'deal_source',
            'deal source'            => 'deal_source',
            'notes'                  => 'notes',
            'tags'                   => 'tags',
            'currency'               => 'currency',
            'region'                 => 'region',
            'location'               => 'region',
            'internal reference id'  => 'internal_reference_id',
            'ref id'                 => 'internal_reference_id',
        ],
        'sample_row' => [
            'deal_name'           => 'Enterprise Software Deal',
            'deal_amount'         => '500000',
            'referrer_email'      => 'referrer@example.com',
            'organization_name'   => 'ABC Company Inc.',
            'deal_stage'          => 'introduction',
            'deal_status'         => 'active',
            'deal_start_date'     => '',
            'expected_close_date' => '',
            'contact_name'        => 'Maria Santos',
            'contact_email'       => 'maria@abccompany.com',
            'contact_phone'       => '+63 9XX XXX XXXX',
            'deal_source'         => 'referral',
            'notes'               => '',
            'partner_emails'      => '',
        ],
    ],

    'saas' => [
        'label'           => 'SaaS / Software',
        'description'     => 'Software deals with subscription and MRR fields.',
        'required_fields' => ['deal_name', 'deal_amount', 'referrer_email', 'organization_name'],
        'optional_fields' => [
            'product_plan', 'subscription_term', 'monthly_recurring_revenue',
            'annual_contract_value', 'expected_close_date', 'contact_name',
            'contact_email', 'partner_emails', 'deal_stage', 'deal_source', 'notes',
        ],
        'default_values'  => [
            'deal_stage'  => 'introduction',
            'deal_status' => 'active',
            'currency'    => 'PHP',
        ],
        'aliases' => [
            'plan'                      => 'product_plan',
            'product plan'              => 'product_plan',
            'subscription'              => 'subscription_term',
            'subscription term'         => 'subscription_term',
            'mrr'                       => 'monthly_recurring_revenue',
            'monthly recurring revenue' => 'monthly_recurring_revenue',
            'acv'                       => 'annual_contract_value',
            'annual contract value'     => 'annual_contract_value',
            // standard aliases
            'deal name'                 => 'deal_name',
            'deal amount'               => 'deal_amount',
            'referrer email'            => 'referrer_email',
            'reseller email'            => 'referrer_email',
            'organization'              => 'organization_name',
            'company'                   => 'organization_name',
            'company name'              => 'organization_name',
            'partner emails'            => 'partner_emails',
            'stage'                     => 'deal_stage',
            'contact email'             => 'contact_email',
        ],
        'sample_row' => [
            'deal_name'                 => 'SaaS Pro Plan — ABC Corp',
            'deal_amount'               => '120000',
            'referrer_email'            => 'referrer@example.com',
            'organization_name'         => 'ABC Corp',
            'product_plan'              => 'Pro',
            'subscription_term'         => '12 months',
            'monthly_recurring_revenue' => '10000',
            'annual_contract_value'     => '120000',
            'expected_close_date'       => '',
            'contact_name'              => 'Juan dela Cruz',
            'contact_email'             => 'juan@abccorp.com',
            'deal_source'               => 'referral',
        ],
    ],

    'retail' => [
        'label'           => 'Retail / Ecommerce',
        'description'     => 'Retail and merchant deals.',
        'required_fields' => ['deal_name', 'deal_amount', 'referrer_email', 'organization_name'],
        'optional_fields' => [
            'product_category', 'order_volume', 'branch_location',
            'contact_name', 'contact_phone', 'partner_emails', 'deal_stage', 'deal_source', 'notes',
        ],
        'default_values'  => [
            'deal_stage'  => 'introduction',
            'deal_status' => 'active',
            'currency'    => 'PHP',
        ],
        'aliases' => [
            'deal name'       => 'deal_name',
            'deal amount'     => 'deal_amount',
            'referrer email'  => 'referrer_email',
            'reseller email'  => 'referrer_email',
            'store name'      => 'organization_name',
            'merchant name'   => 'organization_name',
            'organization'    => 'organization_name',
            'company'         => 'organization_name',
            'category'        => 'product_category',
            'product category'=> 'product_category',
            'volume'          => 'order_volume',
            'order volume'    => 'order_volume',
            'branch'          => 'branch_location',
            'branch location' => 'branch_location',
            'location'        => 'branch_location',
            'contact'         => 'contact_name',
            'contact person'  => 'contact_name',
            'partner emails'  => 'partner_emails',
            'stage'           => 'deal_stage',
        ],
        'sample_row' => [
            'deal_name'        => 'Retail Franchise Deal — XYZ Store',
            'deal_amount'      => '200000',
            'referrer_email'   => 'referrer@example.com',
            'organization_name'=> 'XYZ Store',
            'product_category' => 'Fashion',
            'order_volume'     => '500 units/month',
            'branch_location'  => 'Makati City',
            'contact_name'     => 'Maria Reyes',
            'contact_phone'    => '+63 9XX XXX XXXX',
        ],
    ],

    'fnb' => [
        'label'           => 'F&B / Food and Beverage',
        'description'     => 'Restaurant and food brand deals.',
        'required_fields' => ['deal_name', 'deal_amount', 'referrer_email', 'organization_name'],
        'optional_fields' => [
            'branch_count', 'location', 'cuisine_type',
            'contact_name', 'contact_email', 'partner_emails', 'deal_stage', 'notes',
        ],
        'default_values'  => [
            'deal_stage'  => 'introduction',
            'deal_status' => 'active',
            'currency'    => 'PHP',
        ],
        'aliases' => [
            'deal name'       => 'deal_name',
            'deal amount'     => 'deal_amount',
            'referrer email'  => 'referrer_email',
            'reseller email'  => 'referrer_email',
            'restaurant name' => 'organization_name',
            'brand name'      => 'organization_name',
            'organization'    => 'organization_name',
            'company'         => 'organization_name',
            'branches'        => 'branch_count',
            'branch count'    => 'branch_count',
            'location'        => 'location',
            'cuisine'         => 'cuisine_type',
            'cuisine type'    => 'cuisine_type',
            'contact'         => 'contact_name',
            'partner emails'  => 'partner_emails',
            'stage'           => 'deal_stage',
        ],
        'sample_row' => [
            'deal_name'        => 'F&B Partnership — Jollibee Franchise',
            'deal_amount'      => '1500000',
            'referrer_email'   => 'referrer@example.com',
            'organization_name'=> 'Jollibee Franchise',
            'branch_count'     => '3',
            'location'         => 'Metro Manila',
            'cuisine_type'     => 'Fast Food',
            'contact_name'     => 'Jose Santos',
            'contact_email'    => 'jose@franchise.com',
        ],
    ],

    'beauty' => [
        'label'           => 'Beauty / Wellness',
        'description'     => 'Beauty salon, clinic, and wellness deals.',
        'required_fields' => ['deal_name', 'deal_amount', 'referrer_email', 'organization_name'],
        'optional_fields' => [
            'service_type', 'branch_location', 'contact_name',
            'expected_close_date', 'partner_emails', 'deal_stage', 'notes',
        ],
        'default_values'  => [
            'deal_stage'  => 'introduction',
            'deal_status' => 'active',
            'currency'    => 'PHP',
        ],
        'aliases' => [
            'deal name'      => 'deal_name',
            'deal amount'    => 'deal_amount',
            'referrer email' => 'referrer_email',
            'reseller email' => 'referrer_email',
            'business name'  => 'organization_name',
            'clinic name'    => 'organization_name',
            'salon name'     => 'organization_name',
            'organization'   => 'organization_name',
            'service'        => 'service_type',
            'service type'   => 'service_type',
            'branch'         => 'branch_location',
            'location'       => 'branch_location',
            'contact'        => 'contact_name',
            'partner emails' => 'partner_emails',
            'stage'          => 'deal_stage',
        ],
        'sample_row' => [
            'deal_name'        => 'Beauty Clinic Partnership',
            'deal_amount'      => '300000',
            'referrer_email'   => 'referrer@example.com',
            'organization_name'=> 'Glow Clinic',
            'service_type'     => 'Aesthetic Services',
            'branch_location'  => 'BGC Taguig',
            'contact_name'     => 'Dr. Anna Lim',
        ],
    ],

    'pet' => [
        'label'           => 'Pet Industry',
        'description'     => 'Pet business and merchant deals.',
        'required_fields' => ['deal_name', 'deal_amount', 'referrer_email', 'organization_name'],
        'optional_fields' => [
            'product_or_service', 'store_location',
            'contact_name', 'contact_email', 'partner_emails', 'deal_stage', 'notes',
        ],
        'default_values'  => [
            'deal_stage'  => 'introduction',
            'deal_status' => 'active',
            'currency'    => 'PHP',
        ],
        'aliases' => [
            'deal name'          => 'deal_name',
            'deal amount'        => 'deal_amount',
            'referrer email'     => 'referrer_email',
            'reseller email'     => 'referrer_email',
            'pet business name'  => 'organization_name',
            'merchant name'      => 'organization_name',
            'organization'       => 'organization_name',
            'product'            => 'product_or_service',
            'service'            => 'product_or_service',
            'store location'     => 'store_location',
            'location'           => 'store_location',
            'contact'            => 'contact_name',
            'partner emails'     => 'partner_emails',
            'stage'              => 'deal_stage',
        ],
        'sample_row' => [
            'deal_name'         => 'Pet Supply Partnership',
            'deal_amount'       => '150000',
            'referrer_email'    => 'referrer@example.com',
            'organization_name' => 'Happy Paws Store',
            'product_or_service'=> 'Pet Food & Accessories',
            'store_location'    => 'Quezon City',
            'contact_name'      => 'Ben Cruz',
            'contact_email'     => 'ben@happypaws.com',
        ],
    ],

    'training' => [
        'label'           => 'Training / Events',
        'description'     => 'Corporate training and events deals.',
        'required_fields' => ['deal_name', 'deal_amount', 'referrer_email', 'organization_name'],
        'optional_fields' => [
            'event_date', 'training_type', 'participants',
            'venue', 'contact_name', 'partner_emails', 'deal_stage', 'notes',
        ],
        'default_values'  => [
            'deal_stage'  => 'introduction',
            'deal_status' => 'active',
            'currency'    => 'PHP',
        ],
        'aliases' => [
            'deal name'              => 'deal_name',
            'deal amount'            => 'deal_amount',
            'referrer email'         => 'referrer_email',
            'reseller email'         => 'referrer_email',
            'client name'            => 'organization_name',
            'organization'           => 'organization_name',
            'event date'             => 'event_date',
            'date'                   => 'event_date',
            'training type'          => 'training_type',
            'type'                   => 'training_type',
            'number of participants' => 'participants',
            'pax'                    => 'participants',
            'venue'                  => 'venue',
            'contact'                => 'contact_name',
            'partner emails'         => 'partner_emails',
            'stage'                  => 'deal_stage',
        ],
        'sample_row' => [
            'deal_name'        => 'Leadership Training Program',
            'deal_amount'      => '450000',
            'referrer_email'   => 'referrer@example.com',
            'organization_name'=> 'Acme Corp',
            'event_date'       => '2025-06-15',
            'training_type'    => 'Leadership Development',
            'participants'     => '50',
            'venue'            => 'Manila Hotel',
        ],
    ],

    'ngo' => [
        'label'           => 'NGO / Nonprofit',
        'description'     => 'NGO, nonprofit, and grant deals.',
        'required_fields' => ['deal_name', 'deal_amount', 'referrer_email', 'organization_name'],
        'optional_fields' => [
            'program_area', 'beneficiary_group', 'funding_source',
            'region', 'contact_name', 'partner_emails', 'deal_stage', 'notes',
        ],
        'default_values'  => [
            'deal_stage'  => 'introduction',
            'deal_status' => 'active',
            'currency'    => 'PHP',
        ],
        'aliases' => [
            'deal name'       => 'deal_name',
            'deal amount'     => 'deal_amount',
            'grant value'     => 'deal_amount',
            'referrer email'  => 'referrer_email',
            'reseller email'  => 'referrer_email',
            'organization name'=> 'organization_name',
            'organization'    => 'organization_name',
            'ngo name'        => 'organization_name',
            'nonprofit name'  => 'organization_name',
            'program area'    => 'program_area',
            'program'         => 'program_area',
            'beneficiary'     => 'beneficiary_group',
            'region'          => 'region',
            'funding'         => 'funding_source',
            'funding source'  => 'funding_source',
            'contact'         => 'contact_name',
            'partner emails'  => 'partner_emails',
            'stage'           => 'deal_stage',
        ],
        'sample_row' => [
            'deal_name'         => 'Community Development Program',
            'deal_amount'       => '2000000',
            'referrer_email'    => 'referrer@example.com',
            'organization_name' => 'Gawad Kalinga',
            'program_area'      => 'Housing',
            'beneficiary_group' => 'Urban Poor',
            'funding_source'    => 'Private Donation',
            'region'            => 'Luzon',
        ],
    ],

    'real_estate' => [
        'label'           => 'Real Estate',
        'description'     => 'Real estate and property deals.',
        'required_fields' => ['deal_name', 'deal_amount', 'referrer_email', 'organization_name'],
        'optional_fields' => [
            'property_type', 'location', 'unit_count',
            'contact_name', 'contact_email', 'partner_emails',
            'deal_stage', 'expected_close_date', 'notes',
        ],
        'default_values'  => [
            'deal_stage'  => 'introduction',
            'deal_status' => 'active',
            'currency'    => 'PHP',
        ],
        'aliases' => [
            'deal name'      => 'deal_name',
            'deal amount'    => 'deal_amount',
            'referrer email' => 'referrer_email',
            'reseller email' => 'referrer_email',
            'client name'    => 'organization_name',
            'developer name' => 'organization_name',
            'property name'  => 'organization_name',
            'organization'   => 'organization_name',
            'property type'  => 'property_type',
            'type'           => 'property_type',
            'location'       => 'location',
            'address'        => 'location',
            'units'          => 'unit_count',
            'unit count'     => 'unit_count',
            'buyer contact'  => 'contact_name',
            'contact'        => 'contact_name',
            'partner emails' => 'partner_emails',
            'stage'          => 'deal_stage',
        ],
        'sample_row' => [
            'deal_name'        => 'Condo Unit Pre-Selling — Ayala Land',
            'deal_amount'      => '5000000',
            'referrer_email'   => 'referrer@example.com',
            'organization_name'=> 'Ayala Land',
            'property_type'    => 'Condominium',
            'location'         => 'Alabang, Muntinlupa',
            'unit_count'       => '10',
            'contact_name'     => 'Patricia Reyes',
        ],
    ],

    'professional_services' => [
        'label'           => 'Professional Services',
        'description'     => 'Consulting, legal, accounting, and services deals.',
        'required_fields' => ['deal_name', 'deal_amount', 'referrer_email', 'organization_name'],
        'optional_fields' => [
            'service_type', 'project_scope', 'contract_duration',
            'contact_name', 'contact_email', 'partner_emails',
            'deal_stage', 'expected_close_date', 'notes',
        ],
        'default_values'  => [
            'deal_stage'  => 'introduction',
            'deal_status' => 'active',
            'currency'    => 'PHP',
        ],
        'aliases' => [
            'deal name'         => 'deal_name',
            'deal amount'       => 'deal_amount',
            'referrer email'    => 'referrer_email',
            'reseller email'    => 'referrer_email',
            'client name'       => 'organization_name',
            'company name'      => 'organization_name',
            'organization'      => 'organization_name',
            'service'           => 'service_type',
            'service type'      => 'service_type',
            'scope'             => 'project_scope',
            'project scope'     => 'project_scope',
            'duration'          => 'contract_duration',
            'contract duration' => 'contract_duration',
            'contact'           => 'contact_name',
            'partner emails'    => 'partner_emails',
            'stage'             => 'deal_stage',
        ],
        'sample_row' => [
            'deal_name'         => 'IT Consulting Project',
            'deal_amount'       => '800000',
            'referrer_email'    => 'referrer@example.com',
            'organization_name' => 'BDO Consulting',
            'service_type'      => 'IT Consulting',
            'project_scope'     => 'Digital Transformation',
            'contract_duration' => '6 months',
            'contact_name'      => 'Carlos Mendoza',
        ],
    ],

    'government_generic' => [
        'label'          => 'Government / Public Sector',
        'description'    => 'Generic government agency deals. NOTE: LGU IDS uses its own locked template.',
        'required_fields'=> ['deal_name', 'deal_amount', 'referrer_email', 'organization_name'],
        'optional_fields'=> [
            'region', 'department', 'contact_name', 'procurement_stage',
            'partner_emails', 'deal_stage', 'notes', 'internal_reference_id',
        ],
        'default_values' => [
            'deal_stage'  => 'introduction',
            'deal_status' => 'active',
            'currency'    => 'PHP',
        ],
        // Safety flag: LGU IDS MUST NOT use this template — it has its own locked service.
        'lgu_ids_locked' => true,
        'aliases'        => [
            'deal name'        => 'deal_name',
            'deal amount'      => 'deal_amount',
            'referrer email'   => 'referrer_email',
            'reseller email'   => 'referrer_email',
            'agency name'      => 'organization_name',
            'office name'      => 'organization_name',
            'organization'     => 'organization_name',
            'government agency'=> 'organization_name',
            'region'           => 'region',
            'department'       => 'department',
            'office'           => 'department',
            'contact'          => 'contact_name',
            'contact person'   => 'contact_name',
            'procurement stage'=> 'procurement_stage',
            'partner emails'   => 'partner_emails',
            'stage'            => 'deal_stage',
            'ref'              => 'internal_reference_id',
        ],
        'sample_row' => [
            'deal_name'         => 'Agency Procurement Deal',
            'deal_amount'       => '3000000',
            'referrer_email'    => 'referrer@example.com',
            'organization_name' => 'DICT Region III',
            'region'            => 'Region III',
            'department'        => 'IT Department',
            'contact_name'      => 'Dir. Santos',
            'procurement_stage' => 'Pre-Procurement',
        ],
    ],
];
