@extends('layouts.app')
@section('title','Referrers')
@section('nav') @include('tenant._nav') @endsection
@section('topbar-actions')
@if($program)@can('managePeople',$program)<button class="btn-primary" onclick="document.getElementById('program-invite').showModal()">Invite Referrer</button>@endcan @endif
@endsection
@section('content')
<style>
.pr{color:#241d50}.pr .panel{background:#fff;border:1px solid #e9e2f7;border-radius:18px;padding:22px;margin-bottom:18px}.pr h1{font-size:24px;font-weight:750}.pr h2{font-size:17px;font-weight:700}.pr .muted{color:#817899;font-size:12px;line-height:1.7}.pr .row{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.pr .stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:13px}.pr .stat strong{display:block;font-size:27px;margin-top:8px}.pr a,.pr .text-button{color:#7734ff}.pr input,.pr select,.pr textarea{border:1px solid #e3d9f1;border-radius:10px;padding:10px;background:white;max-width:100%}.pr table{width:100%;font-size:13px;border-collapse:collapse}.pr th{text-align:left;background:#faf8fe;color:#817899;font-size:11px;padding:13px}.pr td{padding:16px 13px;border-bottom:1px solid #f0eaf8}.pr .badge{padding:4px 9px;border-radius:14px;background:#f3edff;color:#7734ff;font-size:11px}.pr button.primary{background:#7734ff;color:white;padding:11px 16px;border-radius:10px}.pr dialog{margin:auto;border:none;border-radius:20px;padding:25px;width:min(690px,94vw);max-height:88vh;color:#241d50}.pr dialog::backdrop{background:#17112a70}.pr dialog label{font-size:12px;display:block}.pr dialog input{width:100%;margin-top:5px}.pr .invite-row{display:grid;grid-template-columns:1fr 1fr auto;gap:12px;margin:14px 0;align-items:end}.pr .invite-row .result{grid-column:1/-1;font-size:12px}.pr .optional{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:14px 0}.pr button:disabled{opacity:.5;cursor:wait}.pr .bulk-tools{display:none;padding:10px 0}.pr .text-button{font-size:12px;text-decoration:underline;cursor:pointer;background:none;border:0}.pr .notice{font-size:13px;margin:12px 0;line-height:1.6}@media(max-width:560px){body:has(.pr) header.sticky{height:auto;min-height:64px;flex-wrap:wrap;padding-top:8px;padding-bottom:8px}body:has(.pr) header.sticky>div:last-child{width:100%;flex-wrap:wrap;gap:8px;justify-content:flex-start}.pr dialog{padding:18px;max-height:90dvh}.pr dialog button{min-height:44px}.pr .stats{grid-template-columns:repeat(2,minmax(0,1fr))}.pr .panel{padding:16px}.pr .stat strong{font-size:22px}.pr #invite-finish{width:100%}.pr .invite-row{grid-template-columns:1fr}.pr .optional{grid-template-columns:1fr}}
</style>
<div class="pr">
@foreach($errors->all() as $error)<p class="panel" role="alert" style="color:#b91c1c">{{ $error }}</p>@endforeach
@if(session('delivery_notice'))<p class="panel" role="status">{{ session('delivery_notice') }}</p>@endif
@if(session('bulk_invite_results'))<section class="panel" role="status"><h2>Resend results</h2>@foreach(session('bulk_invite_results') as $result)<p>{{ $result['email'] }} · {{ $result['message'] }}</p>@endforeach</section>@endif
@if(!$program)<section class="panel"><h1>Referrers</h1><p>Create or select a referral program to manage its referrers.</p><a href="{{ route('tenant.programs.index',$tenant->id) }}">View programs →</a></section>
@else
<section class="panel"><div class="row" style="justify-content:space-between"><div><p class="muted">{{ $program->referralProgramLabel() }}</p><h1>{{ $program->name }} · Referrers</h1></div><form method="GET"><label class="muted" for="referrer-program">Program</label><select name="program_id" id="referrer-program" onchange="this.form.submit()">@foreach($programs as $p)<option value="{{ $p->id }}" @selected($program->id===$p->id)>{{ $p->name }}</option>@endforeach</select></form></div>
<p class="muted" style="margin-top:12px">All-time program activity. Money is shown in {{ $currency }}; clicks, signups and customer counts include all currencies.</p>
<div class="row" style="margin-top:12px">@foreach($program->offers->where('status','active') as $offer)@php $v=$offer->currentVersion;@endphp @if($v && $v->status==='published' && $v->tenant_id===$tenant->id && $v->program_id===$program->id)<span class="badge">{{ $v->reward_model==='percentage'?(float)$v->percentage_rate.'%':($v->reward_model==='fixed'?$v->currency.' '.number_format($v->fixed_amount,2):'Custom') }} reward @if(($v->reward_rules['scope']??'')==='recurring') · {{ $v->reward_rules['duration_months']??'—' }} months @endif @if(isset($v->reward_rules['hold_days'])) · {{ $v->reward_rules['hold_days'] }}-day hold @endif</span>@endif @endforeach <a href="{{ route('tenant.programs.workspace',[$tenant->id,$program->id]) }}?tab=mechanics">Program mechanics →</a></div></section>
<div class="stats">@foreach(['Total referrers'=>$summary['total'],'Active'=>$summary['active'],'Pending invites'=>$summary['invited']] as $label=>$n)<div class="panel stat"><span class="muted">{{ $label }}</span><strong>{{ number_format($n) }}</strong></div>@endforeach
@if($automated)<div class="panel stat"><span class="muted">Clicks</span><strong>{{ number_format($summary['clicks']) }}</strong></div><div class="panel stat"><span class="muted">Signups</span><strong>{{ $summary['signups']===null?'—':number_format($summary['signups']) }}</strong></div><div class="panel stat"><span class="muted">Net recorded rewards</span><strong>{{ $currency }} {{ number_format($summary['rewards'],2) }}</strong><span class="muted">After reversals · not paid out</span></div>@else<div class="panel stat"><span class="muted">Assigned referrals</span><strong>{{ number_format($summary['referrals']) }}</strong><span class="muted">Reward eligibility follows published mechanics.</span></div>@endif</div>
<section class="panel"><div class="row" style="justify-content:space-between"><h2>Invitation funnel</h2><button type="button" class="text-button" onclick="document.getElementById('invite-guide').showModal()">Getting started guide</button></div><p class="muted">All-time people invited to this program. Delivery reflects each person's latest email; joined includes people who joined before a later resend. These counts are not consecutive conversion stages.</p><div class="stats" style="margin-top:12px">@foreach($funnel as $label=>$count)<div class="stat"><span class="muted">{{ $label }}</span><strong>{{ $count }}</strong></div>@endforeach</div></section>
<dialog id="invite-guide" aria-labelledby="invite-guide-title"><h2 id="invite-guide-title">Grow your program in five steps</h2><ol style="padding:18px;line-height:2">
<li><a href="{{ route('tenant.programs.workspace',[$tenant->id,$program->id]) }}?tab=mechanics">Review your program mechanics</a> — confirm rewards, eligibility and dates.</li>
<li><a href="{{ route('tenant.programs.workspace',[$tenant->id,$program->id]) }}">Check your program's name and logo</a> — make it recognizable.</li>
<li>Choose Invite Referrer, then Invite a group to add names or import a CSV. Review recipients and your optional message before sending.</li>
<li>Check delivery and pending membership separately. Select pending invitations to resend, or cancel a pending invitation to withdraw access to this program.</li>
<li>Watch joined referrers and program activity. A signup is not a payment or a reward.</li></ol><form method="dialog"><button class="primary">Done</button></form></dialog>
<section class="panel"><form method="GET" class="row"><input type="hidden" name="program_id" value="{{ $program->id }}"><input name="q" value="{{ $search }}" placeholder="Search name or email" aria-label="Search name or email"><select name="status" aria-label="Membership status"><option value="">All statuses</option>@foreach(['active','invited','approved','paused','suspended','removed','expired'] as $st)<option value="{{ $st }}" @selected($status===$st)>{{ ucfirst($st) }}</option>@endforeach</select><select name="delivery" aria-label="Invitation delivery status"><option value="">All delivery statuses</option>@foreach(['sent'=>'Sent · unconfirmed','delivered'=>'Delivered','failed'=>'Send failed','bounced'=>'Bounced','delayed'=>'Delayed','complained'=>'Spam complaint','suppressed'=>'Suppressed','sending'=>'Sending','untracked'=>'Not tracked'] as $value=>$label)<option value="{{ $value }}" @selected($deliveryFilter===$value)>{{ $label }}</option>@endforeach</select><button class="primary">Filter</button></form></section>
<section class="panel" style="overflow:auto">@can('managePeople',$program)<button type="button" class="text-button" id="bulk-resend-open">Review selected invitations for resend</button><p class="muted">Select up to 20 pending invitations on this page. Expired links must be renewed individually.</p>@endcan<p class="muted">{{ $rows->total() }} referrers · selected program</p><p class="muted">Email delivery is separate from membership. Delivered means the receiving mail server accepted the email, not that it was read. Older invitations may be untracked. Tracked deliveries refresh automatically about every five minutes for 30 days after sending. History retains the latest 50 changes.</p><table><thead><tr><th>REFERRER</th><th>MEMBERSHIP</th><th>INVITE DELIVERY</th>@if($automated)<th>CLICKS</th><th>SIGNUPS</th><th>PAYING CUSTOMERS</th><th>NET REVENUE</th><th>NET REWARDS</th>@else<th>ASSIGNED REFERRALS</th>@endif<th>JOINED</th></tr></thead><tbody>@forelse($rows as $m)<tr><td>@can('managePeople',$program)@if($m->status==='invited' && !$m->reseller->setupExpiresAt()?->isPast())<input type="checkbox" class="invite-select" value="{{ $m->id }}" data-email="{{ $m->reseller->email }}" aria-label="Select invitation for {{ $m->reseller->email }}"> @endif @endcan<strong>{{ $m->reseller->name }}</strong><br><span class="muted">{{ $m->reseller->email }}</span></td><td><span class="badge">{{ isset($m->metadata['invite_cancelled_at'])?'Cancelled':ucfirst($m->status) }}</span></td><td data-invite-delivery="{{ $m->id }}">
@php $delivery=$m->metadata['invite_delivery']??[]; $deliveryLabels=['sending'=>'Sending','sent'=>'Sent · delivery unconfirmed','delivered'=>'Delivered to mail server','failed'=>'Send failed','bounced'=>'Bounced','complained'=>'Spam complaint','delayed'=>'Delivery delayed','suppressed'=>'Suppressed']; @endphp
<span class="badge">{{ $deliveryLabels[$delivery['status']??'']??'Not tracked' }}</span>
@if(!empty($delivery['sent_at']))<br><span class="muted">Sent {{ \Carbon\Carbon::parse($delivery['sent_at'])->setTimezone($program->timezone?:'UTC')->format('M j, g:i A') }} · {{ $program->timezone?:'UTC' }}</span>@endif
@if(!empty($delivery['checked_at']))<br><span class="muted">Checked {{ \Carbon\Carbon::parse($delivery['checked_at'])->diffForHumans() }}</span>@endif
@if($m->status==='invited' && !$m->reseller->password)
@php $expires=$m->reseller->setupExpiresAt(); $last=$m->metadata['invite_last_attempt_at']??$delivery['sent_at']??null; $retryAt=$last?\Carbon\Carbon::parse($last)->addSeconds(($delivery['status']??'')==='failed'?60:600):null; @endphp
<br><span class="muted">{{ $expires?->isPast()?'Setup link expired':'Setup link expires '.($expires?->setTimezone($program->timezone?:'UTC')->format('M j, Y')??'—') }}</span>
@can('managePeople',$program)
@if($expires?->isPast())<form method="POST" action="{{ route('tenant.programs.members.renew',[$tenant->id,$program->id,$m->id]) }}">@csrf<button type="submit" class="text-button">Renew and send invitation</button><p class="muted">Replaces expired setup links for this account with a new 90-day link.</p></form>@endif
@if($expires && !$expires->isPast())<form method="POST" action="{{ route('tenant.programs.members.resend',[$tenant->id,$program->id,$m->id]) }}">@csrf<button type="submit" class="text-button" @disabled($retryAt?->isFuture())>{{ $retryAt?->isFuture()?'Resend available '.$retryAt->setTimezone($program->timezone?:'UTC')->format('g:i A'):'Resend invitation' }}</button></form>@endif
@endcan
@elseif($m->joined_at)<br><span class="muted">Joined · no setup link pending</span>@endif
@if(!empty($delivery['provider_id']))@can('managePeople',$program)<form method="POST" action="{{ route('tenant.programs.members.delivery',[$tenant->id,$program->id,$m->id]) }}">@csrf<button type="submit" class="text-button">Check delivery</button></form>@endcan @endif
@if($m->status==='invited')@can('managePeople',$program)<details><summary class="text-button">Cancel pending invitation</summary><form method="POST" action="{{ route('tenant.programs.members.cancel',[$tenant->id,$program->id,$m->id]) }}">@csrf<p class="muted">Withdraw this person's pending access to {{ $program->name }}. Other programs and their account remain unchanged.</p><label><input type="checkbox" name="confirmed" value="1" required> Confirm cancellation</label><button class="text-button">Cancel this invitation</button></form></details>@endcan @endif
<details style="margin-top:8px"><summary class="text-button">Invitation history</summary><ul class="muted" style="min-width:180px;max-height:220px;overflow:auto">@forelse(array_reverse($m->metadata['invite_history']??[]) as $entry)<li>{{ ucfirst(str_replace('_',' ',$entry['event'])) }} · {{ \Carbon\Carbon::parse($entry['at'])->setTimezone($program->timezone?:'UTC')->format('M j, g:i A') }}</li>@empty<li>No earlier activity recorded.</li>@endforelse @if($m->joined_at)<li>Joined · {{ $m->joined_at->setTimezone($program->timezone?:'UTC')->format('M j, g:i A') }}</li>@endif</ul></details>
</td>@if($automated)<td>{{ $clicks[$m->id]??0 }}</td><td>{{ $sync?($signups[$m->id]??0):'—' }}</td><td>{{ $paid[$m->reseller_id]??0 }}</td><td>{{ $currency }} {{ number_format(($money[$m->reseller_id]->revenue??0)/100,2) }}</td><td>{{ $currency }} {{ number_format(($money[$m->reseller_id]->rewards??0)/100,2) }}</td>@else<td>{{ $leads[$m->reseller_id]??0 }}</td>@endif<td>{{ $m->joined_at?->format('M j, Y')??'Not joined yet' }}</td></tr>@empty<tr><td colspan="10" class="muted">No referrers match this program and filter.</td></tr>@endforelse</tbody></table>{{ $rows->links() }}</section>
@can('managePeople',$program)
<dialog aria-labelledby="invite-title" id="program-invite" data-endpoint="{{ route('tenant.programs.members.invite',[$tenant->id,$program->id]) }}"><div class="row" style="justify-content:space-between"><h2 id="invite-title">Invite Referrer</h2><button type="button" id="invite-close" aria-label="Close invite">×</button></div><p class="muted" id="invite-description">{{ $program->name }} · Each person receives their own program invitation.</p>
<section id="invite-success" hidden aria-live="polite" style="padding:24px 0 8px">
<div aria-hidden="true" style="width:52px;height:52px;border-radius:50%;background:#ecfdf5;color:#059669;display:grid;place-items:center;font-size:28px;margin-bottom:16px">✓</div>
<h2 id="invite-success-title">Invitation sent</h2><p class="muted" style="margin-top:8px">The invitation email includes the link to join this program. New referrers will appear as Invited until they finish setting up their account.</p>
<ul id="invite-receipts" style="margin:16px 0;max-height:220px;overflow:auto;font-size:13px;overflow-wrap:anywhere"></ul>
<button type="button" class="primary" id="invite-finish">View referrers</button>
</section>
<form id="program-invite-form">@csrf<div id="invite-rows"><div class="invite-row"><label>Full name *<input data-name required maxlength="150" placeholder="Juan dela Cruz"></label><label>Email *<input data-email required type="email" maxlength="254" placeholder="juan@email.com"></label><span></span><span class="result" role="status"></span></div></div>
<div class="optional" id="invite-optional"><label>Phone<input id="invite-phone" maxlength="50" placeholder="+63 XXX XXX XXXX"></label><label>Territory<input id="invite-territory" maxlength="150" placeholder="e.g. Metro Manila"></label></div>
<button type="button" class="text-button" id="invite-group">Invite a group</button>
<div class="bulk-tools" id="invite-tools"><label>Find in this batch<input id="invite-search" type="search" placeholder="Search name or email"></label><button type="button" class="text-button" id="invite-import">Import referrers</button> · <button type="button" class="text-button" id="invite-add">+ Add another</button><input hidden type="file" id="invite-file" accept=".csv,text/csv"><p class="muted">CSV columns: name,email. Up to 50 people per batch. Imported names are shown for review before sending.</p></div>
<label style="margin:14px 0">Personal message (optional)<textarea id="invite-message" maxlength="1000" rows="3" style="width:100%;margin-top:5px" placeholder="Tell referrers why you would like them to join."></textarea><span class="muted">Up to 1,000 characters. Included in each invitation in this batch.</span></label>
<button type="button" id="invite-download" class="text-button" hidden>Download failed rows (CSV)</button><p id="invite-progress" role="status" class="notice"></p><div class="row" style="justify-content:flex-end"><button type="button" id="invite-cancel">Cancel</button><button class="primary" id="invite-send" type="submit">Send invitation</button><button type="button" id="invite-done" hidden>View referrers</button></div></form></dialog>
<dialog id="bulk-resend-dialog" aria-labelledby="bulk-resend-title"><h2 id="bulk-resend-title">Review selected invitations</h2><p class="muted">This sends another email to each selected person. Cooldowns still apply. It does not renew expired links.</p><ul id="bulk-resend-recipients" style="padding:14px 0;overflow-wrap:anywhere"></ul><form method="POST" id="bulk-resend-form" action="{{ route('tenant.programs.members.bulk-resend',[$tenant->id,$program->id]) }}">@csrf<div id="bulk-resend-members"></div><label>Personal message (optional)<textarea name="message" maxlength="1000" rows="3" style="width:100%"></textarea></label><label style="margin:16px 0"><input type="checkbox" name="confirmed" value="1" required style="width:auto"> Send invitation emails to these selected recipients.</label><p id="bulk-resend-progress" role="status"></p><div class="row"><button type="button" onclick="this.closest('dialog').close()">Back</button><button type="submit" class="primary">Resend selected invitations</button></div></form></dialog>
<script src="{{ asset('js/program-invite-selection.js') }}" defer></script>
<script src="{{ asset('js/program-referrer-invites.js') }}?v=5" defer></script>
@endcan
@endif
<script src="{{ asset('js/program-invite-delivery-refresh.js') }}" defer></script>
</div>
@endsection
